<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE data [
    <!ELEMENT data (sales,customers)>
    <!ELEMENT sales (sale+)>
    <!ELEMENT sale (purchase_number,date_of_purchase,customer_id,item_code)>
    <!ELEMENT purchase_number (#PCDATA)>
    <!ELEMENT date_of_purchase (#PCDATA)>
    <!ELEMENT customer_id (#PCDATA)>
    <!ELEMENT item_code (#PCDATA)>

    <!ELEMENT customers (customer+)>
    <!ELEMENT customer (customer_id,first_name,last_name,email_address,number_of_complaints)>
    <!ELEMENT first_name (#PCDATA)>
    <!ELEMENT last_name (#PCDATA)>
    <!ELEMENT email_address (#PCDATA)>
    <!ELEMENT number_of_complaints (#PCDATA)>
]>



<data>
    <sales>
        <sale>
            <purchase_number>1</purchase_number>
            <date_of_purchase>2016-09-03</date_of_purchase>
            <customer_id>1</customer_id>
            <item_code>A_1</item_code>
        </sale>
        <sale>
            <purchase_number>2</purchase_number>
            <date_of_purchase>2016-12-02</date_of_purchase>
            <customer_id>2</customer_id>
            <item_code>C_1</item_code>
        </sale>
        <sale>
            <purchase_number>3</purchase_number>
            <date_of_purchase>2017-04-15</date_of_purchase>
            <customer_id>3</customer_id>
            <item_code>D_1</item_code>
        </sale>
        <sale>
            <purchase_number>4</purchase_number>
            <date_of_purchase>2017-05-24</date_of_purchase>
            <customer_id>1</customer_id>
            <item_code>B_2</item_code>
        </sale>
        <sale>
            <purchase_number>5</purchase_number>
            <date_of_purchase>2017-05-25</date_of_purchase>
            <customer_id>4</customer_id>
            <item_code>B_2</item_code>
        </sale>
        <sale>
            <purchase_number>6</purchase_number>
            <date_of_purchase>2017-06-06</date_of_purchase>
            <customer_id>2</customer_id>
            <item_code>B_1</item_code>
        </sale>
        <sale>
            <purchase_number>7</purchase_number>
            <date_of_purchase>2017-06-10</date_of_purchase>
            <customer_id>4</customer_id>
            <item_code>A_2</item_code>
        </sale>
        <sale>
            <purchase_number>8</purchase_number>
            <date_of_purchase>2017-06-13</date_of_purchase>
            <customer_id>3</customer_id>
            <item_code>C_1</item_code>
        </sale>
        <sale>
            <purchase_number>9</purchase_number>
            <date_of_purchase>2017-07-20</date_of_purchase>
            <customer_id>1</customer_id>
            <item_code>A_1</item_code>
        </sale>
        <sale>
            <purchase_number>10</purchase_number>
            <date_of_purchase>2017-08-11</date_of_purchase>
            <customer_id>2</customer_id>
            <item_code>B_1</item_code>
        </sale>
    </sales>
    <customers>
        <customer>
            <customer_id>1</customer_id>
            <first_name>John</first_name>
            <last_name>McKinley</last_name>
            <email_address>john.mackinley@365careers.com</email_address>
            <number_of_complaints>0</number_of_complaints>
        </customer>
        <customer>
            <customer_id>2</customer_id>
            <first_name>Elizabeth</first_name>
            <last_name>McFarlane</last_name>
            <email_address>e.mcfarlane@365careers.com</email_address>
            <number_of_complaints>2</number_of_complaints>
        </customer>
        <customer>
            <customer_id>3</customer_id>
            <first_name>Kevin</first_name>
            <last_name>Lawrence</last_name>
            <email_address>kevin.lawrence@365careers.com</email_address>
            <number_of_complaints>1</number_of_complaints>
        </customer>
        <customer>
            <customer_id>4</customer_id>
            <first_name>Catherine</first_name>
            <last_name>Winnfield</last_name>
            <email_address>c.winnfield@365careers.com</email_address>
            <number_of_complaints>0</number_of_complaints>
        </customer>
    </customers>
</data>
